app = "zeroclaw-3iyz8v83"
primary_region = "lhr"

[build]
  image = "docker.io/cardellier/zeroclaw:latest"

[env]
  ZEROCLAW_ALLOW_PUBLIC_BIND = "true"
  ZEROCLAW_GATEWAY_HOST = "0.0.0.0"
  ZEROCLAW_GATEWAY_PORT = "42617"

[mounts]
  source = "zeroclaw_data"
  destination = "/data"

[vm]
  memory = "2048mb"
  cpu_kind = "shared"
  cpus = 1

[[services]]
  internal_port = 42617
  protocol = "tcp"
  auto_stop_machines = "off"
  auto_start_machines = false

  [[services.ports]]
    port = 80
